version: '3'

services:
  tubesmsbd:
    image: tubesmsbd:latest
    volumes:
      - ./airflow:/opt/airflow
    ports:
      - "8080:8080"
    command: >
      bash -c "
      airflow db init &&
      rm -f /opt/airflow/airflow-webserver.pid &&
      airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com &&
      airflow scheduler & airflow webserver
      "
    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: mysql://root:@mysql/airflow

  mysql:
    image: mysql:latest  
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes" 
      MYSQL_DATABASE: airflow            
    volumes:
      - mysql_data:/var/lib/mysql  
    ports:
    - "3306:3306"
  
  phpmyadmin:
    image: phpmyadmin:latest
    environment:
      PMA_HOST: mysql                    
      PMA_PORT: 3306                       
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes" 
    ports:
      - "8081:80"                         
    depends_on:
      - mysql

  mongodb-bi-connector:
    image: ryanhs/mongodb-bi-connector:latest
    environment:
      MONGODB_HOST: mongo
      MONGODB_PORT: 27017
    ports:
      - "3307:3307"

  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ""
      MONGO_INITDB_ROOT_PASSWORD: ""
    volumes:
      - mongo_data:/data/db
      - ./dump:/dump  
    ports:
      - "28017:27017"


volumes:
  mysql_data:
  mongo_data:
